登録画面で詰まりました
daikisumita/customers pull request #1
Opened 2021-06-23 20:03 UTC by daikisumita

遅くなり申し訳ございません。
登録画面で入力した情報が登録できません。new.phpの63行目がエラーになっているのは分かるのですが原因がわかりません。
教えていただければとおもいます。

2021-06-23 20:40 UTC, kazu-taka requested changes
@daikisumita 
フォームやINSERTのSQLには問題なさそうでした！
修正後再度登録処理を実行し、エラーになった場合はエラーメッセージの共有をお願いします:bow:

2021-06-23 20:40 UTC, kazu-taka commented on new.php
> +if ($company == '') {
@daikisumita 
ここはifの中のコードになるので、インデントするように修正お願いします✨
```php
// フォームに入力されたデータの受け取り
$company = filter_input(INPUT_POST, 'company');
$name = filter_input(INPUT_POST, 'name');
$email = filter_input(INPUT_POST, 'email');
if ($company == '') {
```

2021-06-23 20:40 UTC, kazu-taka commented on new.php
> +}
@daikisumita 
`measurement_date`は体温管理アプリで使用するテーブルのカラムになるので、今回は不要です！
また、会社の重複チェックは仕様にはないので、ここのif文は削除してOKです！！

2021-06-23 20:40 UTC, kazu-taka commented on new.php
> +if (empty($errors)) {
@daikisumita 
ここのifもインデントするように修正お願いします！

2021-06-23 20:40 UTC, kazu-taka commented on new.php
> +<?php if ($errors) : ?>
@daikisumita 
ここのifもインデントするようにお願いします:bow:

2021-06-24 21:03 UTC, kazu-taka requested changes
@daikisumita 
コメントしたので確認お願いします🙏

2021-06-24 21:03 UTC, kazu-taka commented on new.php
> +        $stmt = $dbh->prepare($sql);
@daikisumita 
SQLを使用するために`$dbh`を参照しようとしていますが、new.phpで$dbhが生成されていないためエラーになっています！
`$dbh = connectDb()`の処理を追加してみて下さい👍

2021-07-03 08:02 UTC, yukishimizumg reviewed
@daikisumita 
質問に回答しましたので、コメントの確認お願いします😊🌼

2021-07-03 08:02 UTC, yukishimizumg commented on edit.php
> +    }
体温アプリでは、すでに登録済みの体温であるかどうかのチェックを入れていたのでこのコードを書いていました。
今回はそこはチェックしないので、ここのコードは不要です✨

2021-07-03 08:02 UTC, yukishimizumg commented on edit.php
> +        $errors = '';
変更内容がないときのエラーは、こちらのコードを修正すると、設定できます✨

`編集前の会社名` と `編集後の会社名` が等しい
かつ
`編集前の氏名` と `編集後の氏名` が等しい
かつ
`編集前のメールアドレス` と `編集後のメールアドレス` が等しい場合、
$errorsにエラーメッセージを保存(`$errors[] = '変更内容がありません';`)しましょう✨

`$company` → 編集後の会社名(入力した会社名)
`$ct['company'] `→ 編集前の会社名
になります。
これと同じように氏名とメールアドレスも考えて、コードを修正してみてください✨

2021-07-03 08:42 UTC, daikisumita commented
ご確認ありがとうございます！！！
修正し削除機能まで終わりました！！
ご確認よろしくお願いいたします！！

2021-07-03 09:41 UTC, yukishimizumg reviewed
@daikisumita 
いい感じです！！！
いくつかコメントしましたので、確認お願いします✨

お仕事忙しい中、課題お疲れさまです😊
あと少しなので修正お願いします🙏

2021-07-03 09:41 UTC, yukishimizumg commented on edit.php
> +    $errors[] = '会社名を入力してください';
インデント修正お願いします✨

2021-07-03 09:41 UTC, yukishimizumg commented on edit.php
> +    $ct['email'] == $email) {
インデントの修正お願いします✨

2021-07-03 09:41 UTC, yukishimizumg commented on edit.php
> +    //
コメント付けない場合は削除しましょう✨

2021-07-03 09:41 UTC, yukishimizumg commented on index.php
> +}
タスク管理アプリの残があるので、削除お願いします😊

2021-07-03 09:41 UTC, yukishimizumg commented on index.php
> +/* タスク照会
コメント入れるなら「顧客情報の取得」などがいいと思います^^

2021-07-03 09:41 UTC, yukishimizumg commented on index.php
> +        <?php if ($errors) echo (createErrMsg($errors)) ?>
一覧画面にエラーメッセージ表示しないので、削除お願いします✨

2021-07-03 09:41 UTC, yukishimizumg commented on index.php
> +                            <td><a href=""><?= h($ct['company']) ?></a></td><!-- 会社名を出力 -->
会社名にリンクついてますが、今回は不要なので、aタグ削除しましょう✨

` <td><?= h($ct['company']) ?></td>`

2021-07-03 09:41 UTC, yukishimizumg commented on functions.php
> +}
タスク管理の残だと思うので削除お願いします✨

2021-07-03 10:42 UTC, daikisumita commented
修正致しました！！
どうでしょうか！！

2021-07-03 11:21 UTC, yukishimizumg commented
@daikisumita 

OKなのでマージしてください！！！
お疲れさまでしたっっっっ🎉🎉🎉😆😆

![LGTM](https://image.lgtmoon.dev/5979)

2021-07-03 12:18 UTC, merged